"""Link user and video by id

Revision ID: 8513b6e9838e
Revises: fd3f0c6daf9d
Create Date: 2025-11-25 19:12:06.344817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8513b6e9838e"
down_revision: Union[str, Sequence[str], None] = "fd3f0c6daf9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_videos_author_username"), table_name="videos")
    op.create_index(op.f("ix_videos_user_id"), "videos", ["user_id"], unique=False)
    op.create_foreign_key(None, "videos", "users", ["user_id"], ["id"])
    op.drop_column("videos", "author_username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos",
        sa.Column("author_username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.drop_index(op.f("ix_videos_user_id"), table_name="videos")
    op.create_index(
        op.f("ix_videos_author_username"), "videos", ["author_username"], unique=False
    )
    op.drop_column("videos", "user_id")
    # ### end Alembic commands ###
