"""Init db

Revision ID: fd3f0c6daf9d
Revises:
Create Date: 2025-11-25 18:25:06.076112

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd3f0c6daf9d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "author_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column(
            "voice",
            sa.Enum("rogue", "knight", "wizard", name="voicepreset"),
            nullable=False,
        ),
        sa.Column("subtitle_style_id", sa.Integer(), nullable=False),
        sa.Column(
            "subtitle_position",
            sa.Enum("top", "center", "bottom", name="subtitleposition"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("queued", "processing", "completed", "failed", name="videostatus"),
            nullable=False,
        ),
        sa.Column("video_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumbnail_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_videos_author_username"), "videos", ["author_username"], unique=False
    )
    op.create_index(op.f("ix_videos_status"), "videos", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_videos_status"), table_name="videos")
    op.drop_index(op.f("ix_videos_author_username"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
